using HomeWorks.AdaptorGenerator;

namespace HomeWorks.Tests.AdaptorGenerator
{
    public class AdaptorGeneratorTest
    {
        [Fact]
        public void Test_AutoGeneratedMovableAdapter_NotNull()
        {
            var generator = AutoGeneratedMovableAdapter.Main();

            Assert.NotNull(generator);

        }
    }
}